from autogen_agentchat.teams import RoundRobinGroupChat
from autogen_agentchat.conditions import MaxMessageTermination, TextMentionTermination
from autogen_agentchat.base import TaskResult

from agents import build_agents


async def run_analysis(user_request: str) -> str:
    """
    Run the full multi-agent stock analysis pipeline.

    Agent execution order (enforced by RoundRobinGroupChat):
        1. financial_reporting_analyst  -- fetches fundamentals
        2. technical_analyst            -- adds SMA / EMA / RSI
        3. strategy_agent               -- synthesises Buy/Hold/Sell
        4. supervisor                   -- human relay, receives final output

    Args:
        user_request -- plain-text query, e.g. "Analyse MSFT and give a recommendation."

    Returns:
        The final consolidated Markdown report as a string.
    """
    agents = build_agents()

    # Stop after 20 messages OR when strategy_agent says TERMINATE -- whichever comes first.
    # Without a hard message cap, a misconfigured agent could loop indefinitely.
    termination = (
        MaxMessageTermination(max_messages=20)
        | TextMentionTermination("TERMINATE")
    )

    # ⚠️ Updated from deprecated v0.2 GroupChat/GroupChatManager → v0.4 RoundRobinGroupChat
    team = RoundRobinGroupChat(
        participants=[
            agents["financial_analyst"],
            agents["technical_analyst"],
            agents["strategy_agent"],
            agents["supervisor"],
        ],
        termination_condition=termination,
    )

    result: TaskResult = await team.run(task=user_request)

    # Walk the message history in reverse and return the last meaningful
    # assistant response (skip tool call messages and the TERMINATE line).
    for msg in reversed(result.messages):
        content = getattr(msg, "content", "")
        if isinstance(content, str) and content.strip() and "TERMINATE" not in content:
            return content.strip()

    return "No response generated by the agents."
